const fs = require("fs")
const path = require("path")
const assert = require("assert")

// Load Model.js (plain ECMAScript, no QML deps) into this process.
const src = fs.readFileSync(path.join(__dirname, "..", "Model.js"), "utf8")
const factory = new Function(
  src + "\nreturn { namedRows, numberedRows, numberedRange, pillLabel, jumpTarget, hyprBindsLua, safeMod, safeSection, validKey, defaultWorkspaces, withDefaultWorkspaces };"
)
const Model = factory()

let passed = 0
function check(name, fn) { fn(); passed++; console.log("ok - " + name) }

const config = [
  { key: "W", name: "web", icon: "" },
  { key: "G", name: "G", icon: "" },
]

check("namedRows marks focused + occupied by name", () => {
  const live = [
    { id: 1, name: "web", occupied: true },
    { id: 2, name: "1", occupied: true },
  ]
  const rows = Model.namedRows(config, live, "web")
  assert.strictEqual(rows.length, 2)
  assert.strictEqual(rows[0].name, "web")
  assert.strictEqual(rows[0].focused, true)
  assert.strictEqual(rows[0].occupied, true)
  assert.strictEqual(rows[0].exists, true)
  assert.strictEqual(rows[1].name, "G")
  assert.strictEqual(rows[1].exists, false)
  assert.strictEqual(rows[1].occupied, false)
  assert.strictEqual(rows[1].focused, false)
})

check("numberedRows returns sorted active numerics incl focused", () => {
  const live = [
    { id: 3, name: "3", occupied: true },
    { id: 1, name: "1", occupied: true },
  ]
  const rows = Model.numberedRows(live, 5)
  const keys = rows.map(r => r.key)
  assert.deepStrictEqual(keys, ["1", "3", "5"])
  assert.strictEqual(rows.find(r => r.key === "5").focused, true)
  assert.strictEqual(rows.find(r => r.key === "5").occupied, false)
  assert.strictEqual(rows.every(r => r.kind === "numbered"), true)
})

check("numberedRange lists 1..count with existence + focus", () => {
  const live = [{ id: 2, name: "2", occupied: true }]
  const rows = Model.numberedRange(live, 2, 3)
  assert.deepStrictEqual(rows.map(r => r.key), ["1", "2", "3"])
  assert.strictEqual(rows[0].exists, false)      // ws 1 not created
  assert.strictEqual(rows[0].occupied, false)
  assert.strictEqual(rows[1].exists, true)       // ws 2 exists
  assert.strictEqual(rows[1].occupied, true)
  assert.strictEqual(rows[1].focused, true)
  assert.strictEqual(rows.every(r => r.kind === "numbered"), true)
})

check("pillLabel honors each format", () => {
  const row = { kind: "named", key: "W", name: "web", icon: "◆" }
  assert.strictEqual(Model.pillLabel(row, "key"), "W")
  assert.strictEqual(Model.pillLabel(row, "name"), "web")
  assert.strictEqual(Model.pillLabel(row, "key-name"), "W·web")
  assert.strictEqual(Model.pillLabel(row, "icon"), "◆")
  assert.strictEqual(Model.pillLabel(row, "[{key}] {name}"), "[W] web")
})

check("pillLabel key-name collapses when key equals name", () => {
  const row = { kind: "named", key: "C", name: "C", icon: "" }
  assert.strictEqual(Model.pillLabel(row, "key-name"), "C")
})

check("pillLabel icon falls back to name when icon empty", () => {
  const row = { kind: "named", key: "W", name: "web", icon: "" }
  assert.strictEqual(Model.pillLabel(row, "icon"), "web")
})

check("hyprBindsLua binds keyed+named workspaces, skips incomplete", () => {
  const ws = [
    { key: "W", name: "web" },
    { key: "", name: "nokey" },   // skipped (no key)
    { key: "X", name: "" },        // skipped (no name)
    { key: "K", name: "K" },
  ]
  const lua = Model.hyprBindsLua(ws, "ALT")
  assert.ok(lua.includes('o.bind("ALT + W", "Switch to web workspace", hl.dsp.focus({ workspace = "name:web" }))'))
  assert.ok(lua.includes('o.bind("ALT + SHIFT + W", "Move window to web workspace", hl.dsp.window.move({ workspace = "name:web" }))'))
  assert.ok(lua.includes('o.bind("ALT + K"'))
  assert.ok(!lua.includes("nokey"))
  assert.ok(!lua.includes('name:""'))
  assert.ok(lua.startsWith("-- Generated by kconfesor.hyprsidekick"))
})

check("hyprBindsLua defaults mod to ALT and escapes quotes", () => {
  assert.ok(Model.hyprBindsLua([{ key: "W", name: "web" }]).includes("ALT + W"))
  assert.ok(Model.hyprBindsLua([{ key: "Q", name: 'a"b' }], "SUPER").includes('name:a\\"b'))
})

check("validKey accepts alphanumerics, rejects everything else", () => {
  assert.ok(Model.validKey("W") && Model.validKey("1") && Model.validKey("F5"))
  assert.ok(!Model.validKey('W" }) os.execute("x")'))
  assert.ok(!Model.validKey("a b") && !Model.validKey("code:10") && !Model.validKey(""))
})

check("safeMod whitelists modifier combos, else ALT", () => {
  assert.strictEqual(Model.safeMod("super + alt"), "SUPER + ALT")
  assert.strictEqual(Model.safeMod("CTRL"), "CTRL")
  assert.strictEqual(Model.safeMod('SUPER"}) os.execute("x'), "ALT")
  assert.strictEqual(Model.safeMod(""), "ALT")
  assert.strictEqual(Model.safeMod(null), "ALT")
})

check("safeSection allowlists left/center/right, else left", () => {
  assert.strictEqual(Model.safeSection("right"), "right")
  assert.strictEqual(Model.safeSection("  Center "), "center")
  assert.strictEqual(Model.safeSection("left; rm -rf ~"), "left")
  assert.strictEqual(Model.safeSection(""), "left")
})

check("hyprBindsLua drops injection in key/name/mod", () => {
  const lua = Model.hyprBindsLua([
    { key: 'W" }) os.execute("evil', name: "web" }, // bad key -> skipped
    { key: "N", name: "line1\nrequire('evil')" },    // control char -> skipped
    { key: "G", name: "Games" },                      // clean -> kept
  ], 'SUPER") os.execute("evil')                      // bad mod -> ALT
  assert.ok(!lua.includes("os.execute"))
  assert.ok(!lua.includes("require('evil')"))
  assert.ok(lua.includes('o.bind("ALT + G"'))         // mod fell back to ALT
  assert.ok(!lua.includes('ALT + W'))                 // bad key dropped
})

check("jumpTarget prefixes named, bare numbered", () => {
  assert.strictEqual(Model.jumpTarget({ kind: "named", name: "web" }), "name:web")
  assert.strictEqual(Model.jumpTarget({ kind: "numbered", name: "5" }), "5")
})

check("defaultWorkspaces gives a non-empty starter set with keys+names", () => {
  const d = Model.defaultWorkspaces()
  assert.ok(Array.isArray(d) && d.length >= 3)
  assert.ok(d.every(w => w.key && w.name))
  assert.ok(d.some(w => w.name === "web"))
})

console.log(`\n${passed} checks passed`)
